function SaveToMatFile( tNetwork, strFileName )
	%
	aaiAdjacencyMatrix				= tNetwork.aaiAdjacencyMatrix; %#ok<NASGU>
	aafNodesPositions				= tNetwork.aafNodesPositions; %#ok<NASGU>
	iNumberOfNodes					= tNetwork.iNumberOfNodes; %#ok<NASGU>
	strKindOfGraph					= tNetwork.strKindOfGraph; %#ok<NASGU>
	fCommunicationRadius			= tNetwork.fCommunicationRadius; %#ok<NASGU>
	aiBidimensionalGridDimensions	= tNetwork.aiBidimensionalGridDimensions; %#ok<NASGU>
	strCommunicationKind			= tNetwork.strCommunicationKind; %#ok<NASGU>
	bUseSelfLoops					= tNetwork.bUseSelfLoops; %#ok<NASGU>
	aiSenders						= tResults.aiSenders; %#ok<NASGU>
	aacReceivers					= tResults.aacReceivers; %#ok<NASGU>
	%
	save(	strFileName,							...
			'aaiAdjacencyMatrix',					...
			'aafNodesPositions',					...
			'iNumberOfNodes',						...
			'strKindOfGraph',						...
			'fCommunicationRadius',					...
			'aiBidimensionalGridDimensions',		...
			'strCommunicationKind',					...
			'bUseSelfLoops',						...
			'aiSenders',							...
			'aacReceivers',							...
			'-V6'); % saving format
	%
end %

