function SaveToMatFile( tCommunicationsManager, strFileName )
	%
	aaiAdjacencyMatrix				= tCommunicationsManager.tGraph.GetAdjacencyMatrix(); %#ok<NASGU>
	aafNodesPositions				= tCommunicationsManager.tGraph.aafNodesPositions; %#ok<NASGU>
	iNumberOfNodes					= tCommunicationsManager.tGraph.iNumberOfNodes; %#ok<NASGU>
	strKindOfGraph					= tCommunicationsManager.strKindOfGraph; %#ok<NASGU>
	fCommunicationRadius			= tCommunicationsManager.fCommunicationRadius; %#ok<NASGU>
	aiBidimensionalGridDimensions	= tCommunicationsManager.aiBidimensionalGridDimensions; %#ok<NASGU>
	strCommunicationKind			= tCommunicationsManager.strCommunicationKind; %#ok<NASGU>
	bUseSelfLoops					= tCommunicationsManager.bUseSelfLoops; %#ok<NASGU>
	aiSenders						= tResults.aiSenders; %#ok<NASGU>
	aacReceivers					= tResults.aacReceivers; %#ok<NASGU>
	%
	save(	strFileName,							...
			'aaiAdjacencyMatrix',					...
			'aafNodesPositions',					...
			'iNumberOfNodes',						...
			'strKindOfGraph',						...
			'fCommunicationRadius',					...
			'aiBidimensionalGridDimensions',		...
			'strCommunicationKind',					...
			'bUseSelfLoops',						...
			'aiSenders',							...
			'aacReceivers',							...
			'-V6'); % saving format
	%
end %

